### PR TITLE
Assign operators

### PR DESCRIPTION
**Pull request by FreeCX**
Add rust 1.8 assign operators

### CODE REVIEW

**Comment by citrux** [comment]
Code, implementing SmthAssign trait, repeats code of Smth trait. And I don't know workaround like

``` cpp
Vec2 operator+(Vec2 a, const Vec2 & b) { return a += b; }
```

**Comment by FreeCX** [comment]
@citrux, maybe

``` rust
impl Add for Vec2 {
    type Output = Self;

    fn add(self, _rhs: Self) -> Self {
        let mut a = self;
        a += _rhs;
        a
    }
}
```

But this is not the best solution

**Comment by citrux** [comment]
This variant is longer than duplicated code.

**Comment by FreeCX** [comment]
So I think that we shouldn't rewriting them.

**Pull request merged**
